add update hook and update hooks-api dependency version
auth0-extensions/node-auth0 pull request #4
Opened 2019-09-18 16:44 UTC by faroceann

### Changes

Added update hook 

### References

https://auth0team.atlassian.net/browse/DXEX-273

### Testing

[ 🚫] This change adds unit test coverage
[ 🚫] This change adds integration test coverage

### Checklist
[ ✅] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
[ ✅] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
[ 🚫] All existing and new tests complete without errors

2019-09-19 07:31 UTC, zxan1285 requested changes

2019-09-19 07:31 UTC, zxan1285 commented on src/management/HooksManager.js
> + * management.hooks.update(data, function (err) {
Shouldn't it be `update(params, data, callback)`? Like in https://github.com/auth0-extensions/node-auth0/blob/master/src/management/ClientsManager.js#L147
Same for `get` and `delete` - there should be an object, not just plain `id`.

2019-09-20 14:30 UTC, shawnmclean commented on src/management/HooksManager.js
> + * management.hooks.update(data, function (err) {
It should be, but since this is mostly a POC and we're just using it to pull into deploy cli, this is fine. We'll be rewriting the whole slice in an official PR to the node library anyways.

2019-09-20 14:30 UTC, merged

2019-09-20 14:50 UTC, zxan1285 commented on src/management/HooksManager.js
> + * management.hooks.update(data, function (err) {
`source-control-tools` depends on `node-auth0` SDK consistency. Here https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/default.js#L186-L188 all handlers are using `update` method in the same way. So we have to either change the SDK or override `processChanges` method of `hooks` handler in the `source-control-tools`.